###* 1) REGISTRO
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "email": "a@a.net",
    "password": "12345678"
}

###* 2) VALIDACIÓN DE MAIL
POST http://localhost:4000/api/auth/verify-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODk0YzBiNjI2OTcwMzk5NDRiNmIiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjExMDc5NiwiZXhwIjoxNzQ2MTE3OTk2fQ.NVO0uOi14ulQRoC9XtPm0ZGRsPKSAfRkKdpDAaO-AJs

{
    "code": "924770"
}


###* 3) LOGIN
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "email": "a@a.net",
    "password": "12345678"
}

###*4) PUT
PATCH http://localhost:4000/api/user/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODVmNTgzYTE5NWFkZTA2OTNlY2YiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjEwOTk5NSwiZXhwIjoxNzQ2MTE3MTk1fQ.84_nIi6vsLfP2JBEsBEzPq6b37GZJQLSXqFD7cE0aZQ

{
    "email" : "ejemplo@gmail.com",
    "name" : "ejemplo",
    "surnames" : "apellidos",
    "nif" : "12345678Z"
}

###* 4) PATCH
PATCH http://localhost:4000/api/user/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODVmNTgzYTE5NWFkZTA2OTNlY2YiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjEwOTk5NSwiZXhwIjoxNzQ2MTE3MTk1fQ.84_nIi6vsLfP2JBEsBEzPq6b37GZJQLSXqFD7cE0aZQ

{
   "company": {
      "name": "ASDFASDF",
      "cif": "B12345678",
      "street": "PRUEBA STREET",
      "number": 1,
      "postal": 12345,
      "city": "PRUEBA CITY",
      "province": "PRUEBA PROVINCIA"
    }
}

###* 5) PATCH LOGO
PATCH http://localhost:4000/api/user/logo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODVmNTgzYTE5NWFkZTA2OTNlY2YiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjEwOTk5NSwiZXhwIjoxNzQ2MTE3MTk1fQ.84_nIi6vsLfP2JBEsBEzPq6b37GZJQLSXqFD7cE0aZQ

--boundary123
Content-Disposition: form-data; name="image"; filename="star-icon.jpg"
Content-Type: image/jpeg

< ./logos/star-icon.jpg
--boundary123--


###* 6) GET USER
GET http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODVmNTgzYTE5NWFkZTA2OTNlY2YiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjEwOTk5NSwiZXhwIjoxNzQ2MTE3MTk1fQ.84_nIi6vsLfP2JBEsBEzPq6b37GZJQLSXqFD7cE0aZQ


###* 6) DELETE USER HARD DELETE
DELETE http://localhost:4000/api/user?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODVmNTgzYTE5NWFkZTA2OTNlY2YiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjEwOTk5NSwiZXhwIjoxNzQ2MTE3MTk1fQ.84_nIi6vsLfP2JBEsBEzPq6b37GZJQLSXqFD7cE0aZQ

###* 6) DELETE USER SOFT DELETE
DELETE http://localhost:4000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODEzODVmNTgzYTE5NWFkZTA2OTNlY2YiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjEwOTk5NSwiZXhwIjoxNzQ2MTE3MTk1fQ.84_nIi6vsLfP2JBEsBEzPq6b37GZJQLSXqFD7cE0aZQ

###* 6) CONTRASEÑA - ENVIAMOS CÓDIGO (MODIFICAMOS CÓDIGO)
POST http://localhost:4000/api/user/recover
Content-Type: application/json

{
    "email": "ejemplo@gmail.com"
}

###* 6) CONTRASEÑA - VALIDAMOS EL CÓDIGO

PUT http://localhost:4000/api/user/validation
Content-Type: application/json

{
    "email": "ejemplo@gmail.com",
    "code": "513003"
}

###* 6) MODIFICAMOS LA CONTRASEÑA

PATCH http://localhost:4000/api/user/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJpYXQiOjE3NDM0MTk5MzUsImV4cCI6MTc0MzQyNzEzNX0.G1QdYTQCC0vs2CbY4g3rJXXH1g9TNX-VyDim2sANglk

{
    "password" : "12345678"
}


###* 6) INVITACIÓN A UNA PERSONA
POST http://localhost:4000/api/user/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDA1NTUwOSwiZXhwIjoxNzQ0MDYyNzA5fQ.V7p7mDYIbv6jbO6yq8vGX_YDBIfYBPEsBgOsmKIzSoo
Content-Type: application/json

{
  "email": "quintessential.falcon.zfhk@letterhaven.net"
}


########################* PRÁCTICA FINAL
##* CORREO
POST http://localhost:4000/api/mail
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDA1MjgzNiwiZXhwIjoxNzQ0MDYwMDM2fQ.aWuntpr9smz1ywmhOwrOhfuA6oE2Jl83L8WtwMG3_Ho

{
    "subject": "holi",
    "text": "holi buenas",
    "to": "correo@live.u-tad.com",
    "from": "hola@gmail.com"
}


######################* CLIENTS ###############################
##* 1.1) CREATE  client
POST http://localhost:4000/api/client
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyOTUxOCwiZXhwIjoxNzQ0MTM2NzE4fQ.2EvOafgdFP3bjYIR-nefHzFk-NVK5GZpqHUpFQuTzsE

{
  "name": "ACS",
  "cif": "D52921210",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###* 1.2) PATCH client
PATCH http://localhost:4000/api/client/67f5585f13c315993b698121
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyOTUxOCwiZXhwIjoxNzQ0MTM2NzE4fQ.2EvOafgdFP3bjYIR-nefHzFk-NVK5GZpqHUpFQuTzsE

{
  "name": "ABCD",
  "cif": "D52921210",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###* 2.1) GET clients
GET http://localhost:4000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyOTUxOCwiZXhwIjoxNzQ0MTM2NzE4fQ.2EvOafgdFP3bjYIR-nefHzFk-NVK5GZpqHUpFQuTzsE

###* 2.2) GET client by id
GET http://localhost:4000/api/client/67f5585f13c315993b698121
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyOTUxOCwiZXhwIjoxNzQ0MTM2NzE4fQ.2EvOafgdFP3bjYIR-nefHzFk-NVK5GZpqHUpFQuTzsE

###* 3.1) DELETE client (soft) -> archivar
DELETE http://localhost:4000/api/client/archive/67f56182456e517098d93e3f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyOTUxOCwiZXhwIjoxNzQ0MTM2NzE4fQ.2EvOafgdFP3bjYIR-nefHzFk-NVK5GZpqHUpFQuTzsE

###* 3.2) DELETE client (hard)
DELETE http://localhost:4000/api/client/67f5592afaa28dc46bb93a33
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyOTUxOCwiZXhwIjoxNzQ0MTM2NzE4fQ.2EvOafgdFP3bjYIR-nefHzFk-NVK5GZpqHUpFQuTzsE

###* 4.1) GET clientes archivados
GET http://localhost:4000/api/client/archive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyOTUxOCwiZXhwIjoxNzQ0MTM2NzE4fQ.2EvOafgdFP3bjYIR-nefHzFk-NVK5GZpqHUpFQuTzsE

###* 4.2) PATCH (recuperar) cliente archivado
PATCH http://localhost:4000/api/client/recover/67f56182456e517098d93e3f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEyOTUxOCwiZXhwIjoxNzQ0MTM2NzE4fQ.2EvOafgdFP3bjYIR-nefHzFk-NVK5GZpqHUpFQuTzsE


######################* PROJECTS ###############################
##* 1.1) POST un project
POST http://localhost:4000/api/project
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEzNzkzOCwiZXhwIjoxNzQ0MTQ1MTM4fQ.GU1p-QvQer0dM73DdZEjM81kqRXcg2wjqhEI-0wFRFw

{
  "name": "Nombre del proyecto 1",
  "projectCode": "Identificador de proyecto",
  "email": "mimail@gmail.com",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "code": "Código interno del proyecto",
  "clientId": "67f56182456e517098d93e3f"
}


###* 1.2) PATCH de projecto
PATCH http://localhost:4000/api/project/67f56f7d214069f766f80b86
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTQzNzcxMSwiZXhwIjoxNzQ1NDQ0OTExfQ.AUX7pGiTzKyYDKSRXEkg8iR8QR15laOd2KC1nrOqmgU

{
  "name": "obra",
  "code": "00001-01",
  "projectCode": "100000",
  "email": "mimail@gmail.com",
  "clientId": "67f42cb57fab4fadc6eaeeba",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "notes": "XXX XXX XXXX"
}


###* 2.1) GET de todos los proyectos
GET http://localhost:4000/api/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEzNzkzOCwiZXhwIjoxNzQ0MTQ1MTM4fQ.GU1p-QvQer0dM73DdZEjM81kqRXcg2wjqhEI-0wFRFw

###* 2.2) GET de un proyecto específico
GET http://localhost:4000/api/project/one/67f56f7d214069f766f80b86
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTQzNzcxMSwiZXhwIjoxNzQ1NDQ0OTExfQ.AUX7pGiTzKyYDKSRXEkg8iR8QR15laOd2KC1nrOqmgU

###* 3.1) DELETE project (soft) -> archivar
DELETE http://localhost:4000/api/project/archive/67f572d6f6b774fa67eb1220
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEzNzkzOCwiZXhwIjoxNzQ0MTQ1MTM4fQ.GU1p-QvQer0dM73DdZEjM81kqRXcg2wjqhEI-0wFRFw

###* 3.2) DELETE project (hard) -> eliminar definitivamente
DELETE http://localhost:4000/api/project/67f56f7d214069f766f80b86
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEzNzkzOCwiZXhwIjoxNzQ0MTQ1MTM4fQ.GU1p-QvQer0dM73DdZEjM81kqRXcg2wjqhEI-0wFRFw


###* 4.1)
GET http://localhost:4000/api/project/archive
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEzNzkzOCwiZXhwIjoxNzQ0MTQ1MTM4fQ.GU1p-QvQer0dM73DdZEjM81kqRXcg2wjqhEI-0wFRFw

###* 4.2) PATCH (recuperar) cliente archivado
PATCH http://localhost:4000/api/project/recover/67f572d6f6b774fa67eb1220
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2Y0MmNiNTdmYWI0ZmFkYzZlYWVlYmEiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDEzNzkzOCwiZXhwIjoxNzQ0MTQ1MTM4fQ.GU1p-QvQer0dM73DdZEjM81kqRXcg2wjqhEI-0wFRFw



######################* DELIVERY NOTES ###############################
#* -------------------------------------------------------------
#* 1) POST: Crear albarán
#* -------------------------------------------------------------
POST http://localhost:4000/api/deliverynote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTI2MTMyMiwiZXhwIjoxNzQ1MjY4NTIyfQ.zqXiO7pk3b9UScR-CYLPq41nGAgJLbMySLPXGK9rj4A

{
  "clientId": "67f56118132ecbe949246382",
  "projectId": "67f571846332151d8bcc575c",
  "format": "materials",
  "description": "my description",
  "materials": [
    {
      "name": "Cemento",
      "quantity": 10,
      "unit": "sacos"
    },
    {
      "name": "Arena",
      "quantity": 20,
      "unit": "kg"
    }
  ],
  "date": "2024-02-01"
}
###* 1.1)

POST http://localhost:4000/api/deliverynote
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTI2MTMyMiwiZXhwIjoxNzQ1MjY4NTIyfQ.zqXiO7pk3b9UScR-CYLPq41nGAgJLbMySLPXGK9rj4A

{
  "clientId": "67f56118132ecbe949246382",
  "projectId": "67f571846332151d8bcc575c",
  "format": "both",
  "description": "Instalación completa: montaje + materiales usados",
  "workers": [
    {
      "name": "Juan García",
      "hours": 5
    },
    {
      "name": "María López",
      "hours": 4.5
    }
  ],
  "materials": [
    {
      "name": "Cemento",
      "quantity": 10,
      "unit": "sacos"
    },
    {
      "name": "Arena",
      "quantity": 20,
      "unit": "kg"
    }
  ],
  "date": "2024-02-01"
}

###*
#* -------------------------------------------------------------
#* 2) GET: Listar albaranes
#* -------------------------------------------------------------
GET http://localhost:4000/api/deliverynote 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDIyMjYyOSwiZXhwIjoxNzQ0MjI5ODI5fQ.E-c3VhXSso-ME9d4aYQVc6-zBAsD9OXj37btN9Q4f8s


###
#* -------------------------------------------------------------
#* 3) GET: Mostrar 1 albarán concreto
#* -------------------------------------------------------------
GET http://localhost:4000/api/deliverynote/67f6c3792cc5eb7a7af72591
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDIyMjYyOSwiZXhwIjoxNzQ0MjI5ODI5fQ.E-c3VhXSso-ME9d4aYQVc6-zBAsD9OXj37btN9Q4f8s

###
#* -------------------------------------------------------------
#* 4) GET: Descargar/generar albarán en PDF
#* -------------------------------------------------------------
GET http://localhost:4000/api/deliverynote/pdf/67f6c3792cc5eb7a7af72591
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDIyMjYyOSwiZXhwIjoxNzQ0MjI5ODI5fQ.E-c3VhXSso-ME9d4aYQVc6-zBAsD9OXj37btN9Q4f8s


###
#* -------------------------------------------------------------
#* 5) POST: Firmar un albarán (subiendo la imagen a IPFS)
#* -------------------------------------------------------------

POST http://localhost:4000/api/deliverynote/67f6c3792cc5eb7a7af72591/sign HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NDIyMjYyOSwiZXhwIjoxNzQ0MjI5ODI5fQ.E-c3VhXSso-ME9d4aYQVc6-zBAsD9OXj37btN9Q4f8s
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="signature"; filename="firma.png"
Content-Type: image/png

< ./signatures/firma.png
--boundary123--


###
#* -------------------------------------------------------------
#* 6) DELETE: Borrar un albarán
#* -------------------------------------------------------------
DELETE http://localhost:4000/api/deliverynote/680694e15df93f4576dbb11c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NTI2MTMyMiwiZXhwIjoxNzQ1MjY4NTIyfQ.zqXiO7pk3b9UScR-CYLPq41nGAgJLbMySLPXGK9rj4A
