###* 1) REGISTRO
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
    "email": "ejemplo@gmail.com",
    "password": "12345678"
}

###* 2) VALIDACIÓN DE MAIL
POST http://localhost:5000/api/auth/verify-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzAxMTA3NCwiZXhwIjoxNzQzMDE4Mjc0fQ.dsYH1M-ZWH_MNzcxbzEEEHNOaJdZiJJwBaXmDwmPnCo

{
    "code": "475987"
}


###* 3) LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "email": "ejemplo@gmail.com",
    "password": "12345678"
}

###*4) PUT
PUT http://localhost:5000/api/user/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlZTQzZDQyN2ZlMDJmNzQ1NzdkODQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY2MDg5NSwiZXhwIjoxNzQyNjY4MDk1fQ.rRT0koEAPeKUr2is101otuDKjJs9Sr9qFfxsjVps9h8

{
    "email" : "ejemplo@gmail.com",
    "name" : "ejemplo",
    "surnames" : "apellidos",
    "nif" : "12345678Z"
}

###* 4) PATCH
PATCH http://localhost:5000/api/user/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlZTQzZDQyN2ZlMDJmNzQ1NzdkODQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY2MDg5NSwiZXhwIjoxNzQyNjY4MDk1fQ.rRT0koEAPeKUr2is101otuDKjJs9Sr9qFfxsjVps9h8

{
   "company": {
      "name": "ASDFASDF",
      "cif": "B12345678",
      "street": "PRUEBA STREET",
      "number": 1,
      "postal": 12345,
      "city": "PRUEBA CITY",
      "province": "PRUEBA PROVINCIA"
    }
}

###* 5) PATCH LOGO
PATCH http://localhost:5000/api/user/logo HTTP/1.1
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlZTQzZDQyN2ZlMDJmNzQ1NzdkODQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY2MDg5NSwiZXhwIjoxNzQyNjY4MDk1fQ.rRT0koEAPeKUr2is101otuDKjJs9Sr9qFfxsjVps9h8

--boundary123
Content-Disposition: form-data; name="image"; filename="star-icon.jpg"
Content-Type: image/jpeg

< ./logos/star-icon.jpg
--boundary123--


###* 6) GET USER
GET http://localhost:5000/api/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlZTQzZDQyN2ZlMDJmNzQ1NzdkODQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY2MDg5NSwiZXhwIjoxNzQyNjY4MDk1fQ.rRT0koEAPeKUr2is101otuDKjJs9Sr9qFfxsjVps9h8


###* 6) DELETE USER HARD DELETE
DELETE http://localhost:5000/api/user?soft=false
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlZTQzZDQyN2ZlMDJmNzQ1NzdkODQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY2MDg5NSwiZXhwIjoxNzQyNjY4MDk1fQ.rRT0koEAPeKUr2is101otuDKjJs9Sr9qFfxsjVps9h8

###* 6) DELETE USER SOFT DELETE
DELETE http://localhost:5000/api/user
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlZTQzZDQyN2ZlMDJmNzQ1NzdkODQiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MjY2MDg5NSwiZXhwIjoxNzQyNjY4MDk1fQ.rRT0koEAPeKUr2is101otuDKjJs9Sr9qFfxsjVps9h8

###* 6) CONTRASEÑA - ENVIAMOS CÓDIGO (MODIFICAMOS CÓDIGO)
POST http://localhost:5000/api/user/recover
Content-Type: application/json

{
    "email": "ejemplo@gmail.com"
}

###* 6) CONTRASEÑA - VALIDAMOS EL CÓDIGO

PUT http://localhost:5000/api/user/validation
Content-Type: application/json

{
    "email": "ejemplo@gmail.com",
    "code": "793975"
}

###* 6) MODIFICAMOS LA CONTRASEÑA

PATCH http://localhost:5000/api/user/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U0M2QwMjJiNjA5MTM0ZWU4OGE4NzMiLCJpYXQiOjE3NDMwMTQyOTcsImV4cCI6MTc0MzAyMTQ5N30.rZk5AVQv6e7A63b0LpqvVmVkOoF2NJ2g36_49os8MOc

{
    "password" : "87654321"
}